df <- read.table('household_power_consumption.txt', nrow = 2880, sep = ';', h = F, skip = 66637)
NameDf <- readLines('household_power_consumption.txt', n = 1)
names(df) <- unlist(strsplit(NameDf,';'))
png('plot2.png', width = 480, height = 480)
plot(df$Global_active_power, type = "n", axes = F, xlab = "", ylab = "Global Active Power(kilowatts)")
lines(df$Global_active_power)
axis(1, c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
axis(2, c(0, 2, 4, 6))
box()
dev.off()
