df <- read.table('household_power_consumption.txt', nrow = 2880, sep = ';', h = F, skip = 66637)
NameDf <- readLines('household_power_consumption.txt', n = 1)
names(df) <- unlist(strsplit(NameDf,';'))
png('plot4.png', width = 480, height = 480)
par(mfrow = c(2, 2))
plot(df$Global_active_power, type = "n", axes = F, xlab = "", ylab = "Global Active Power")
lines(df$Global_active_power)
axis(1, c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
axis(2, c(0, 2, 4, 6))
box()
plot(df$Voltage, type = "n", axes = F, xlab = "", ylab = "Voltage")
lines(df$Voltage)
axis(1, c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
axis(2, c(234, 238, 242, 246))
box()
plot(df$Sub_metering_1, type = "n", axes = F, xlab = "", ylab = "Energy sub metering")
lines(df$Sub_metering_1, col = "black")
lines(df$Sub_metering_2, col = "red")
lines(df$Sub_metering_3, col = "blue")
legend("topright", legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),
       col = c("black", "red", "blue"), lty = c(1, 1, 1), bty = "n")
axis(1, c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
axis(2, c(0, 10, 20, 30))
box()
plot(df$Global_reactive_power, type = "n", axes = F, xlab = "", ylab = "Global_reactive_power")
lines(df$Global_reactive_power)
axis(1, c(0, 1440, 2880), labels = c("Thu", "Fri", "Sat"))
axis(2, c(0.0, 0.1, 0.2, 0.3, 0.4, 0.5))
box()
dev.off()
